-- MySQL Script generated by MySQL Workbench
-- 08/09/17 10:15:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Group15_Database_Travel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Group15_Database_Travel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Group15_Database_Travel` ;
USE `Group15_Database_Travel` ;

-- -----------------------------------------------------
-- Table `Group15_Database_Travel`.`Plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group15_Database_Travel`.`Plan` (
  `Plan_ID` INT NOT NULL,
  `Plan_Name` VARCHAR(45) NULL,
  PRIMARY KEY (`Plan_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group15_Database_Travel`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group15_Database_Travel`.`Users` (
  `User_ID` INT NOT NULL,
  `User_username` VARCHAR(45) NOT NULL,
  `User_surname` VARCHAR(45) NOT NULL,
  `User_firstname` VARCHAR(45) NULL,
  `User_email` VARCHAR(45) NOT NULL,
  `User_password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`User_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group15_Database_Travel`.`Locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group15_Database_Travel`.`Locations` (
  `Loc_ID` INT NOT NULL,
  `Loc_name` VARCHAR(45) NOT NULL,
  `Loc_description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Loc_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group15_Database_Travel`.`Attractions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group15_Database_Travel`.`Attractions` (
  `Attr_ID` INT NOT NULL,
  `Attr_name` VARCHAR(45) NOT NULL,
  `Attr_description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Attr_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group15_Database_Travel`.`Hotels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group15_Database_Travel`.`Hotels` (
  `Hotel_ID` INT NOT NULL,
  `Hotel_Name` VARCHAR(45) NOT NULL,
  `Hotel_Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Hotel_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group15_Database_Travel`.`Plan_Locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group15_Database_Travel`.`Plan_Locations` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group15_Database_Travel`.`Plan_Attractions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group15_Database_Travel`.`Plan_Attractions` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group15_Database_Travel`.`Plan_Hotels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group15_Database_Travel`.`Plan_Hotels` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
